services:
  consent-manager:
    container_name: "consent-manager"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: consent-manager:latest
    ports:
      - "${PORT}:${PORT}"
    links:
      - mongodb
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - consent-manager
      - ptx

  mongodb:
    container_name: "consent-manager-mongodb"
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - consent_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'consent-manager-mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    networks:
      - consent-manager

networks:
  consent-manager:
    name: consent-manager
    driver: bridge
  ptx:
    name: ptx
    external: true

volumes:
  consent_data:
