replicaCount: 1

image:
  repository: consent-manager
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

env:
  NODE_ENV: development
  PORT: "3000"
  APP_ENDPOINT: "http://localhost:3000"
  MONGO_URI: "mongodb://your_mongo_host:27017/consent-manager"
  MONGO_URI_TEST: "mongodb://your_mongo_host:27017/consent-manager-test"
  API_PREFIX: "/v1"
  SALT_ROUNDS: "10"
  PDI_ENDPOINT: "http://localhost:3331"
  APPLICATION_NAME: "consentmanager-pdi"
  FEDERATED_APPLICATION_IDENTIFIER: "http://localhost:3000"
  SESSION_COOKIE_NAME: "consentmanagersessid"
  SESSION_SECRET: "secret123"
  JWT_SECRET_KEY: "secret123"
  OAUTH_SECRET_KEY: "abc123secret"
  OAUTH_TOKEN_EXPIRES_IN: "1h"
  CONTRACT_SERVICE_BASE_URL: "http://localhost:3000/contracts"
  WINSTON_LOGS_MAX_FILES: "14d"
  WINSTON_LOGS_MAX_SIZE: "20m"
  NODEMAILER_HOST: ""
  NODEMAILER_PORT: ""
  NODEMAILER_USER: "abc@domain.com"
  NODEMAILER_PASS: "pass"
  NODEMAILER_FROM_NOREPLY: '"abc <abc@domain.com>"'
  MANDRILL_ENABLED: "false"
  MANDRILL_API_KEY: "yourkey"
  MANDRILL_FROM_EMAIL: "noreply@domain.com"
  MANDRILL_FROM_NAME: "noreply"
  PRIVACY_RIGHTS: ""
  WITHDRAWAL_METHOD: ""
  CODE_OF_CONDUCT: ""
  IMPACT_ASSESSMENT: ""
  AUTHORITY_PARTY: ""
