apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent-manager
  namespace: consent-manager
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: consent-manager
  template:
    metadata:
      labels:
        app: consent-manager
    spec:
      containers:
        - name: consent-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.service.port } }
          envFrom:
            - secretRef:
                name: env-vars
