apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: consent-manager
type: Opaque
data:
  NODE_ENV: { { .Values.env.NODE_ENV | b64enc } }
  PORT: { { .Values.env.PORT | b64enc } }
  APP_ENDPOINT: { { .Values.env.APP_ENDPOINT | b64enc } }
  MONGO_URI: { { .Values.env.MONGO_URI | b64enc } }
  MONGO_URI_TEST: { { .Values.env.MONGO_URI_TEST | b64enc } }
  API_PREFIX: { { .Values.env.API_PREFIX | b64enc } }
  SALT_ROUNDS: { { .Values.env.SALT_ROUNDS | b64enc } }
  PDI_ENDPOINT: { { .Values.env.PDI_ENDPOINT | b64enc } }
  APPLICATION_NAME: { { .Values.env.APPLICATION_NAME | b64enc } }
  FEDERATED_APPLICATION_IDENTIFIER:
    { { .Values.env.FEDERATED_APPLICATION_IDENTIFIER | b64enc } }
  SESSION_COOKIE_NAME: { { .Values.env.SESSION_COOKIE_NAME | b64enc } }
  SESSION_SECRET: { { .Values.env.SESSION_SECRET | b64enc } }
  JWT_SECRET_KEY: { { .Values.env.JWT_SECRET_KEY | b64enc } }
  OAUTH_SECRET_KEY: { { .Values.env.OAUTH_SECRET_KEY | b64enc } }
  OAUTH_TOKEN_EXPIRES_IN: { { .Values.env.OAUTH_TOKEN_EXPIRES_IN | b64enc } }
  CONTRACT_SERVICE_BASE_URL:
    { { .Values.env.CONTRACT_SERVICE_BASE_URL | b64enc } }
  WINSTON_LOGS_MAX_FILES: { { .Values.env.WINSTON_LOGS_MAX_FILES | b64enc } }
  WINSTON_LOGS_MAX_SIZE: { { .Values.env.WINSTON_LOGS_MAX_SIZE | b64enc } }
  NODEMAILER_HOST: { { .Values.env.NODEMAILER_HOST | b64enc } }
  NODEMAILER_PORT: { { .Values.env.NODEMAILER_PORT | b64enc } }
  NODEMAILER_USER: { { .Values.env.NODEMAILER_USER | b64enc } }
  NODEMAILER_PASS: { { .Values.env.NODEMAILER_PASS | b64enc } }
  NODEMAILER_FROM_NOREPLY: { { .Values.env.NODEMAILER_FROM_NOREPLY | b64enc } }
  MANDRILL_ENABLED: { { .Values.env.MANDRILL_ENABLED | b64enc } }
  MANDRILL_API_KEY: { { .Values.env.MANDRILL_API_KEY | b64enc } }
  MANDRILL_FROM_EMAIL: { { .Values.env.MANDRILL_FROM_EMAIL | b64enc } }
  MANDRILL_FROM_NAME: { { .Values.env.MANDRILL_FROM_NAME | b64enc } }
  PRIVACY_RIGHTS: { { .Values.env.PRIVACY_RIGHTS | b64enc } }
  WITHDRAWAL_METHOD: { { .Values.env.WITHDRAWAL_METHOD | b64enc } }
  CODE_OF_CONDUCT: { { .Values.env.CODE_OF_CONDUCT | b64enc } }
  IMPACT_ASSESSMENT: { { .Values.env.IMPACT_ASSESSMENT | b64enc } }
  AUTHORITY_PARTY: { { .Values.env.AUTHORITY_PARTY | b64enc } }
